### ISSUE TITLE
ADD support for negative sync (audio is ahead of video)

### ISSUE THREAD

**Issue by allanlaal** [adrian-ilie/av-sync#4]
## use case

audio is ahead of video

#3 and #1 kinda rely on this too :)

**Comment by adrian-ilie** [comment]
Thanks for the suggestion, I added this option in v0.0.9!

I have not included this in the original version because it was meant to only solve the problem of out of sync audio when streaming to another device or bluetooth headphones, so the audio will always be behind of the video in those cases.
