### ISSUE TITLE
Add on/off setting for the add-on

### ISSUE THREAD

**Issue by jvdburgh** [adrian-ilie/av-sync#7]
Hi! Awesome add-on, works great to sync audio when using Bluetooth speakers! Thanks for your work!

One feature I would really like is to be able to turn the sync delay on or off, something like this:
![afbeelding](https://user-images.githubusercontent.com/25548343/111869739-0d307c80-8981-11eb-8cbd-dc7d222266e5.png)

Or perhaps a quick setting when clicking on the add-on icon? 

This way, when switching from one audio output to another, you don't have to change the ms each time, and you keep the carefully selected amount of ms for the next time around. Another idea, custom presets?

Cheers!
Killed_Mufasa

**Comment by adrian-ilie** [comment]
Hi, 
Actually, I've added a new menu with this option in the last version (v.0.2.0) 
You should be seeing the extension's icon right next to the settings button in the player. Could you please check that you have the latest version?
![image](https://user-images.githubusercontent.com/64861697/111880492-40d4cc00-89ac-11eb-99cd-629ea0dc2582.png)

**Comment by jvdburgh** [comment]
That's great to hear! That looks very useful! That said, I'm afraid I don't have that menu right now, I'm currently on 0.1.3 and there doesn't seem to be a update on the store yet: https://addons.mozilla.org/nl/firefox/addon/youtube-av-sync/?utm_content=addons-manager-reviews-link&utm_medium=firefox-browser&utm_source=firefox-browser (last updated, 8 months ago). Am I doing something wrong perhaps?

**Comment by jvdburgh** [comment]
v0.2.0 doesn't seem to be live yet: https://addons.mozilla.org/nl/firefox/addon/youtube-av-sync/versions/ :(

**Comment by adrian-ilie** [comment]
Currently v0.2.0 is only available for Chrome: https://chrome.google.com/webstore/detail/youtube-audiovideo-sync/mknmhikmjljhpccebpnplhicmcfjkgbk
It will soon come to Firefox as well (as soon as I get some time to work on it)

**Comment by jvdburgh** [comment]
Oh, I see. That explains it. I hope you can find the time to work on it, but no hurries. Cheers!
