### ISSUE TITLE
not working anymore 

### ISSUE THREAD

**Issue by smenes** [adrian-ilie/av-sync#8]
Hi sir
A few week ago this extension have stop working properly.
I have an hourglass icon and no sound.
![Image](https://i.imgur.com/nTmNEAU.png)

I thinks the problem is from a change from youtube  and not from the browser because I use another extension for youtube and it broke in a same time .

I had also try with different os and a older version of browser and the problem persist.

arch linux with Chromium 96
and windows 10 with Chromium 91

~~if I clear the browser cache (and tick all the options) and I refresh the page, its working. but if I change the video it stop and I have to redo the manip again.~~

A few other people have report this bug on the page for your extension.

I hope this can help

thanks for your time
best regards

**Comment by underwoodblog** [comment]
I can confirm that. Testen with latest Chrome and fresh Vivaldi installation on windows 10 and different computers. No audio. Hope you fix it soon. Thanks!

**Comment by Mahmud-mustafa** [comment]
No longer works in brave V1.34.81

**Comment by adrian-ilie** [comment]
Bug was solved in #9 
Many thanks to @sirluky for fixing the issue!
It should work now if you get the latest version of the extension v0.3.6.

**Comment by smenes** [comment]
Thanks !
